### ISSUE TITLE
Memory leaks in Release (after script backtrace feature)

### ISSUE THREAD

**Issue by Bromeon** [godotengine/godot#105834]
### Tested versions

Godot 4.5-dev, commits see below.

### System information

`godot.linuxbsd.template_release.x86_64`

### Issue description

Our test suite that uses several GDScripts now reports memory leaks on shutdown:
```yaml
ERROR: 7 resources still in use at exit.
   at: clear (core/io/resource.cpp:629)
Resource still in use: res://ManualFfiTests.gd (GDScript)
Resource still in use: res://TestSuite.gd (GDScript)
Resource still in use: res://gen/GenFfiTests.gd (GDScript)
Resource still in use: res://InheritTests.gd (GDScript)
Resource still in use: res://ScriptInstanceTests.gd (GDScript)
Resource still in use: res://SpecialTests.gd (GDScript)
Resource still in use: res://TestSuiteSpecial.gd (GDScript)
```

Example CI run: [Link](https://github.com/godot-rust/gdext/actions/runs/14691896007/job/41228359616#step:3:1702)

A bisect showed that the problem started appearing as of the following commit (thanks @yarwin):

* First bad commit: 28089c40c13597bf908802c61352c6fffe0a4465 (PR https://github.com/godotengine/godot/pull/91006)
* Last good commit: 500e0d5dc407697217663c134031da00e9dfa625

Maybe a bit of background, our GDScript tests run some manually written assertions, and collect some error stats. They also enable/disable engine printing. I wonder if any of that is related to the changes in the first bad commit. See e.g. [`TestSuite.gd`](https://github.com/godot-rust/gdext/blob/master/itest/godot/TestSuite.gd) and [`TestSuiteSpecial.gd`](https://github.com/godot-rust/gdext/blob/master/itest/godot/TestSuiteSpecial.gd)

### Steps to reproduce

The problem appeared in Release build (export templates in headless mode), I didn't see it in Debug/Editor builds.

I couldn't reproduce it with just a simple GDScript file + Rust GDExtension, so I wonder what's needed.

### Minimal reproduction project (MRP)

N/A
