### ISSUE TITLE
Add Bitrise CI for macOS and iOS builds

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#14768]
I've been plying for a couple of days with Bitrise CI because they have free support for macOS, and also because it seems they don't have the problem with the huge backlog Travis CI has. Also the guys from support are very nice and responsive too (thanks @viktorbenei)

If you want to add Bitrise CI for macOS and iOS for Godot, here is what you need to do:

After you log in at Bitrise.io, go to **Add new app**, pick the Godot repository from the GitHub tab. 

In the **Validation setup** step you might prefer the manual configuration for the master branch, otherwise it'll look for Xcode project files to try to guess the project build configuration.

In the **Project build configuration** step there is also a manual setup, it's at the bottom of the tab **MANUAL**, there you'll find the option for Xcode 7.3.1

After the webhooks in the last step are in place go to the dashboard, after clicking **FINISH** at the top, and then to the newly created application, the one for Godot, then to the tab **Code** and copy the app's API token. The API token is for the field `api_token` in the bitrise.yml file below.

```
---
format_version: 1.4.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- push_branch: "*"
  workflow: osx
- pull_request_target_branch: "*"
  workflow: osx
workflows:
  _run_from_repo:
    steps:
    - activate-ssh-key:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone: {}
    - script:
        title: Continue from repo
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            if [ -f .bitrise.yml ] || [ -f bitrise.yml ]; then
              ln -s .bitrise.yml bitrise.yml || true
              bitrise run "${BITRISE_TRIGGERED_WORKFLOW_ID}"
            else
              echo "Nothing to do here... file .bitrise.yml not found!"
            fi
  osx:
    steps:
    - trigger-bitrise-workflow@0.0.1:
        inputs:
        - workflow_id: iphone
        - api_token: XXXXXXXXXXXXXXXXXXXXXX
        is_always_run: true
    after_run:
    - _run_from_repo
  iphone:
    after_run:
    - _run_from_repo
```

Then go to the tab **Workflow** and paste the contents of the file **bitrise.yml** including the API token in the web-ui editor, then save.

The **bitrise.yml** is a wrapper that runs the file **.bitrise.yml** in the repository.

It seems in the future the wrapper won't be needed, since they are [planning to add](https://stackoverflow.com/a/47736608/1436359) a default wrapper that will look for the **bitrise.yml** file in the repo.

The contents of the file **.bitrise.yml** that needs to be added to the repo are below

```
format_version: "4"

default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

project_type: macos

app:
  envs:
    - SCONS_CACHE_ROOT: $HOME/.scons_cache
    - SCONS_CACHE_LIMIT: 1024
    - CC: clang
    - CXX: clang++

workflows:
  _build:
    steps:
      - cache-pull: {}
      - script:
          title: Build script
          inputs:
            - content: |-
                mkdir -p $SCONS_CACHE
                misc/bitrise/scons-local-osx.sh
                scons -j 2 CC=$CC CXX=$CXX platform=$GODOT_TARGET TOOLS=$TOOLS verbose=yes progress=no;
      - cache-push:
          inputs:
            - cache_paths: |-
                $SCONS_CACHE_ROOT

  osx:
    envs:
    - SCONS_CACHE: $SCONS_CACHE_ROOT/osx
    - GODOT_TARGET: osx
    - TOOLS: yes
    after_run:
      - _build

  iphone:
    envs:
    - SCONS_CACHE: $SCONS_CACHE_ROOT/iphone
    - GODOT_TARGET: iphone
    - TOOLS: no
    after_run:
      - _build
```

A few things to point out is that builds are not parallel, although they [will be adding](https://discuss.bitrise.io/t/how-to-have-a-separate-cache-per-workflow/3517/5?u=rraallvv) that in the future, also the cache have to be shared between macOS and iOS, each with a separate folder within the SCONS_CACHE_ROOT folder.

I'm using the script below to install SCons, it has to be copied to `misc/bitrise/scons-local-osx.sh` in the repo

```
#!/bin/bash

echo
echo "Download and install Scons local package ..."
echo

echo "Downloading sources ..."
curl -L -O http://prdownloads.sourceforge.net/scons/scons-local-3.0.0.zip # latest version available here: http://scons.org/pages/download.html

echo "Extracting to build directory ..."
unzip -qq -n scons-local-3.0.0.zip -d $BITRISE_SOURCE_DIR/scons-local

echo "Installing symlinks ..."
ln -s $BITRISE_SOURCE_DIR/scons-local/scons.py /usr/local/bin/scons

echo
echo "Done!"
echo 
```

Please let know any concern you might have, or whether you need me to create a pull request with everything, except for the **bitrise.yml** wrapper that needs to be copied directly to Bitrise workflow editor on the web-ui.

Cheers!
