### ISSUE TITLE
"scons -h" doesn't print help anymore

### ISSUE THREAD

**Issue by merumelu** [godotengine/godot#17497]
**Godot version:**
fe93459ef9ded290277dff0d29747b9336077238

**OS/device including version:**
Probably all where you can build Godot

**Issue description:**
Previously, running `scons -h` would list all the options you can set when compiling Godot. This isn't true anymore, now SCons will just print the normal `No valid target platform selected.` message and exit.

It seems it was already this way before 3.0 was released, and it is broken on the 2.1 branch as well but  does work for `2.1.4-stable`:
<details>

```
scons: Reading SConscript files ...
No valid target platform selected.
The following were detected:
	x11
	server
	haiku

Please run scons again with argument: platform=<string>
scons: done reading SConscript files.

arch: Platform-dependent architecture (arm/arm64/x86/x64/mips/etc)
    default: 
    actual: 

bits: Target platform bits (default/32/64/fat)
    default: default
    actual: default

p: Platform (alias for 'platform')
    default: 
    actual: 

platform: Target platform: any in ['x11', 'server', 'haiku']
    default: 
    actual: 

target: Compilation target (debug/release_debug/release)
    default: debug
    actual: debug

tools: Build the tools a.k.a. the Godot editor (yes/no)
    default: yes
    actual: yes

deprecated: Enable deprecated features (yes/no)
    default: yes
    actual: yes

gdscript: Build GDSCript support (yes/no)
    default: yes
    actual: yes

minizip: Build minizip archive support (yes/no)
    default: yes
    actual: yes

xml: XML format support for resources (yes/no)
    default: yes
    actual: yes

disable_3d: Disable 3D nodes for smaller executable (yes/no)
    default: no
    actual: no

disable_advanced_gui: Disable advance 3D gui nodes and behaviors (yes/no)
    default: no
    actual: no

extra_suffix: Custom extra suffix added to the base filename of all generated binary files
    default: 
    actual: 

unix_global_settings_path: UNIX-specific path to system-wide settings. Currently only used for templates
    default: 
    actual: 

verbose: Enable verbose output for the compilation (yes/no)
    default: no
    actual: no

vsproj: Generate Visual Studio Project. (yes/no)
    default: no
    actual: no

vsproj_jobs: Number of parallel builds
    default: 2
    actual: 2

warnings: Set the level of warnings emitted during compilation (extra/all/moderate/no)
    default: no
    actual: no

progress: Show a progress indicator during build (yes/no)
    default: yes
    actual: yes

dev: If yes, alias for verbose=yes warnings=all
    default: no
    actual: no

builtin_freetype: Use the builtin freetype library (yes/no)
    default: yes
    actual: yes

builtin_glew: Use the builtin glew library (yes/no)
    default: yes
    actual: yes

builtin_libmpcdec: Use the builtin libmpcdec library (yes/no)
    default: yes
    actual: yes

builtin_libogg: Use the builtin libogg library (yes/no)
    default: yes
    actual: yes

builtin_libpng: Use the builtin libpng library (yes/no)
    default: yes
    actual: yes

builtin_libtheora: Use the builtin libtheora library (yes/no)
    default: yes
    actual: yes

builtin_libvorbis: Use the builtin libvorbis library (yes/no)
    default: yes
    actual: yes

builtin_libwebp: Use the builtin libwebp library (yes/no)
    default: yes
    actual: yes

builtin_openssl: Use the builtin openssl library (yes/no)
    default: yes
    actual: yes

builtin_opus: Use the builtin opus library (yes/no)
    default: yes
    actual: yes

builtin_speex: Use the builtin speex library (yes/no)
    default: yes
    actual: yes

builtin_squish: Use the builtin squish library (yes/no)
    default: yes
    actual: yes

builtin_zlib: Use the builtin zlib library (yes/no)
    default: yes
    actual: yes

CXX: C++ compiler
    default: None
    actual: g++

CC: C compiler
    default: None
    actual: gcc

CCFLAGS: Custom flags for the C and C++ compilers
    default: None
    actual: 

CFLAGS: Custom flags for the C compiler
    default: None
    actual: 

LINKFLAGS: Custom flags for the linker
    default: None
    actual: 

use_llvm: Use llvm compiler
    default: no
    actual: no

use_static_cpp: link stdc++ statically
    default: no
    actual: no

use_sanitizer: Use llvm compiler sanitize address
    default: no
    actual: no

use_leak_sanitizer: Use llvm compiler sanitize memory leaks
    default: no
    actual: no

use_lto: Use link time optimization
    default: no
    actual: no

pulseaudio: Detect & Use pulseaudio
    default: yes
    actual: yes

udev: Use udev for gamepad connection callbacks
    default: no
    actual: no

debug_release: Add debug symbols to release version
    default: no
    actual: no

debug_release: Add debug symbols to release version
    default: no
    actual: no

use_llvm: Use llvm compiler
    default: no
    actual: no

force_32_bits: Force 32 bits binary
    default: no
    actual: no

module_opus_enabled: Enable module 'opus' (yes/no)
    default: yes
    actual: yes

module_gdscript_enabled: Enable module 'gdscript' (yes/no)
    default: yes
    actual: yes

module_gridmap_enabled: Enable module 'gridmap' (yes/no)
    default: yes
    actual: yes

module_vorbis_enabled: Enable module 'vorbis' (yes/no)
    default: yes
    actual: yes

module_etc1_enabled: Enable module 'etc1' (yes/no)
    default: yes
    actual: yes

module_dds_enabled: Enable module 'dds' (yes/no)
    default: yes
    actual: yes

module_ik_enabled: Enable module 'ik' (yes/no)
    default: yes
    actual: yes

module_pbm_enabled: Enable module 'pbm' (yes/no)
    default: yes
    actual: yes

module_speex_enabled: Enable module 'speex' (yes/no)
    default: yes
    actual: yes

module_theora_enabled: Enable module 'theora' (yes/no)
    default: yes
    actual: yes

module_freetype_enabled: Enable module 'freetype' (yes/no)
    default: yes
    actual: yes

module_openssl_enabled: Enable module 'openssl' (yes/no)
    default: yes
    actual: yes

module_cscript_enabled: Enable module 'cscript' (yes/no)
    default: yes
    actual: yes

module_chibi_enabled: Enable module 'chibi' (yes/no)
    default: yes
    actual: yes

module_jpg_enabled: Enable module 'jpg' (yes/no)
    default: yes
    actual: yes

module_pvr_enabled: Enable module 'pvr' (yes/no)
    default: yes
    actual: yes

module_ogg_enabled: Enable module 'ogg' (yes/no)
    default: yes
    actual: yes

module_mpc_enabled: Enable module 'mpc' (yes/no)
    default: yes
    actual: yes

module_squish_enabled: Enable module 'squish' (yes/no)
    default: yes
    actual: yes

module_webp_enabled: Enable module 'webp' (yes/no)
    default: yes
    actual: yes

Use scons -H for help about command-line options.
```

</details>

**Steps to reproduce:**
run `scons -h`
