### ISSUE TITLE
CSG doesn't work well when rotated

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#18496]
**Godot version:**

d0183ef Antergos x86_64

**Issue description:**

This is supposed to be a large box subtracted by three smaller boxes:
![image](https://user-images.githubusercontent.com/26753932/39402078-3e8df704-4b80-11e8-819f-315ae835a7b2.png)

**Steps to reproduce:**
1. add a csgcombiner and 2 boxes
2. enlarge & rotate the first box ~60 deg
3. set the second box to subtract & rotate ~60 deg
4. move the second box around

**Minimal reproduction project:**

<details>

```toml
[gd_scene format=2]

[node name="CSGCombiner" type="CSGCombiner" index="0"]
layers = 1
operation = 0
use_collision = true
snap = 0.001

[node name="CSGBox" type="CSGBox" parent="." index="0"]
transform = Transform( 0.5, -0.866025, 0, 0.866025, 0.5, 0, 0, 0, 1, 0, -2.57876, 0 )
layers = 1
operation = 0
use_collision = false
snap = 0.001
invert_faces = false
width = 1.61221
height = 12.6843
depth = 13.2466
material = null
_sections_unfolded = [ "Transform" ]

[node name="CSGBox2" type="CSGBox" parent="." index="1"]
transform = Transform( 0.202111, -0.979362, 0, 0.979362, 0.202111, 0, 0, 0, 1, -1.55954, -0.666089, -1.69563 )
layers = 1
operation = 2
use_collision = false
snap = 0.001
invert_faces = false
width = 1.43675
height = 1.73469
depth = 1.87069
material = null
_sections_unfolded = [ "Transform" ]

[node name="CSGBox3" type="CSGBox" parent="." index="2"]
transform = Transform( 0.202111, -0.979362, 0, 0.979362, 0.202111, 0, 0, 0, 1, -0.655538, -0.852648, -9.56554 )
layers = 1
operation = 2
use_collision = false
snap = 0.001
invert_faces = false
width = 1.43675
height = 1.73469
depth = 1.87069
material = null
_sections_unfolded = [ "Transform" ]

[node name="CSGBox4" type="CSGBox" parent="." index="3"]
transform = Transform( 0.202111, -0.979362, 0, 0.979362, 0.202111, 0, 0, 0, 1, 5.69247, -4.37342, 7.61299 )
layers = 1
operation = 2
use_collision = false
snap = 0.001
invert_faces = false
width = 1.43675
height = 1.73469
depth = 1.87069
material = null
_sections_unfolded = [ "Transform" ]
```

</details>
