### ISSUE TITLE
CI for Linux editor builds with Mono installs .NET 6, but uses .NET 8

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#86374]
### Tested versions

N/a

### System information

N/a

### Issue description

Our CI setup for Linux editor builds with Mono has a step to install .NET 6:

```
      - name: Set up .NET Sdk
        uses: actions/setup-dotnet@v3
        if: ${{ matrix.build-mono }}
        with:
          dotnet-version: '6.0.x'
```

And it does do something. However, in the next step where we build .NET solutions, we don't actually use .NET 6. Logs suggest we're using MSBuild 17.8 which equals SDK 8.0.1xx:

```
MSBuild version 17.8.3+195e7f5a3 for .NET
```

See https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs. At the same time, on our build server we do actually use .NET 6 / C# 10.

```
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
```

This means that builds which pass the CI do not build on the actual build server we use for official distributions. It also means we can accidentally bump our minimum supported version of .NET requirement for our internal solutions. This happened with https://github.com/godotengine/godot/pull/82983 and https://github.com/godotengine/godot/pull/85975, which passed CI but failed on the build server.

----

We need to either decide to actually bump the version (and update the build server), or fix up the CI and be more careful in the future.

### Steps to reproduce

N/a

### Minimal reproduction project (MRP)

N/a
