### ISSUE TITLE
F-Droid can't build `release` Android editor

### ISSUE THREAD

**Issue by licaon-kter** [godotengine/godot#90528]
### Tested versions

Bad: 4.2.1-stable b09f793
Good: 4.1.2-stable 399c9dc

### System information

Debian Bookworm

### Issue description

I'm trying to update the Editor recipe for F-Droid: https://f-droid.org/en/packages/org.godotengine.editor.v4/

### Steps to reproduce

Reading https://docs.godotengine.org/en/4.2/contributing/development/compiling/compiling_for_android.html#building-the-godot-editor

Kinda the same recipe as with 4.1.2 (ignore the versionCode)
```
  - versionName: 4.2.1.stable                                                                                                  
    versionCode: 402025003                                                                                                     
    commit: b09f793f564a6c95dc76acc654b390e68441bd01                                                                           
    timeout: 15000                                                                                                             
    sudo:                                                                                                                      
      - apt-get update                                                                                                         
      - apt-get install -y pkg-config scons                                                                                    
    output: platform/android/java/editor/build/outputs/apk/debug/android_editor-debug-unsigned.apk                             
    prebuild:                                                                                                                                         
      - cd platform/android/java                                                                                               
      - sed -i 's/url repoUrl//' app/build.gradle                                                                              
      - sed -i 's/versionCode\ generateVersionCode()/versionCode $$VERCODE$$/' editor/build.gradle                             
      - sed -i -e 's!sdk_root + "/cmdline-tools/latest/bin/sdkmanager"!"/usr/bin/sdkmanager"!'                                 
        ../detect.py                                                                                                           
    build:                                                                                                                     
      - export ANDROID_SDK_ROOT="$$SDK$$"                                                                                      
      - scons platform=android arch=arm64 production=yes target=editor                                                         
      - cd platform/android/java                                                                                               
      - gradle generateGodotEditor
```
...the last `sed` is to remove a hardcoded path, whatever

Result: `ERROR: Could not build app org.godotengine.editor.v4: Wrong package ID - build org.godotengine.editor.v4.debug but expected org.godotengine.editor.v4`

Umm, but I don't want to build `debug`, and I did not ask for `debug`

Maybe if I ask for `release`
```
    prebuild:                                                                                                                  
      - sed -i -e 's/in \["editor", "template_debug"\]/in \["editor", "template_release"\]/' SConstruct
```
Nope, still: `ERROR: Could not build app org.godotengine.editor.v4: Wrong package ID - build org.godotengine.editor.v4.debug but expected org.godotengine.editor.v4`

Oh, I know, let's use the old trick:
```
prebuild:                                                                                                                  
      - sed -i -e 's/in \["editor", "template_debug"\]/== "template_debug"/' SConstruct
```
...what the
```
modules/gdscript/gdscript_analyzer.cpp:3406:19: error: use of undeclared identifier 'GDScriptWarning'; did you mean 'GDScriptParser'?
modules/gdscript/gdscript_analyzer.cpp:3406:36: error: no member named 'get_settings_path_from_code' in 'GDScriptParser'
modules/gdscript/gdscript_analyzer.cpp:3406:64: error: use of undeclared identifier 'GDScriptWarning'; did you mean 'GDScriptParser'?
...
modules/gdscript/gdscript_editor.cpp:851:45: error: use of undeclared identifier 'GDScriptWarning'; did you mean 'GDScriptParser'?
modules/gdscript/gdscript_editor.cpp:851:62: error: no member named 'WARNING_MAX' in 'GDScriptParser'
modules/gdscript/gdscript_editor.cpp:852:103: error: no member named 'Code' in 'GDScriptParser'
modules/gdscript/gdscript_editor.cpp:852:49: error: use of undeclared identifier 'GDScriptWarning'; did you mean 'GDScriptParser'?
...
DScriptParser'?
modules/gdscript/language_server/gdscript_extend_parser.cpp:147:49: error: use of undeclared identifier 'get_warnings'
modules/gdscript/language_server/gdscript_extend_parser.cpp:148:13: error: unknown type name 'GDScriptWarning'; did you mean 'GDScriptParser'?
modules/gdscript/language_server/gdscript_extend_parser.cpp:151:38: error: no member named 'get_name' in 'GDScriptParser'
modules/gdscript/language_server/gdscript_extend_parser.cpp:151:67: error: no member named 'get_message' in 'GDScriptParser'
modules/gdscript/language_server/gdscript_extend_parser.cpp:153:29: error: no member named 'code' in 'GDScriptParser'
modules/gdscript/language_server/gdscript_extend_parser.cpp:156:43: error: no member named 'start_line' in 'GDScriptParser'
```

### Minimal reproduction project (MRP)

Ok, so, what now, how do I build `org.godotengine.editor.v4.apk` exactly?
