### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by cpusam** [godotengine/godot#9523]
**Operating system or device - Godot version:**
From my unknown users:
Android version: Android 6.0
Device: Y55s (1610)
RAM (MB): 3072
Display size: 720 × 1280
Dpi: 320
Native Platform: armeabi-v7a
OpenGL ES: 3.0
CPU: Qualcomm
CPU: MSM8917

Game made with version 2.1.3

**Issue description:**

```

backtrace:
  native: pc 0000000000c68bf0  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+164)
  native: pc 00000000000b6290  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+47664)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b6290  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+47664)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b0654  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+24052)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b6290  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+47664)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b0654  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+24052)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b0654  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+24052)
  native: pc 00000000000c91ac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance17_ml_call_reversedEP8GDScriptRK10StringNamePPK7Varianti+204)
  native: pc 00000000000c9210  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance24call_multilevel_reversedERK10StringNamePPK7Varianti+36)
  native: pc 00000000006358a8  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Node2D14_notificationvEib+116)
  native: pc 0000000000d71c50  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object12notificationEib+24)
  native: pc 00000000003e1b4c  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN4Node9_set_treeEP9SceneTree+92)
  native: pc 00000000003e1acc  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN4Node18_add_child_nocheckEPS_RK10StringName+88)
  native: pc 00000000003d0da4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN11MethodBind1IP4NodeE4callEP6ObjectPPK7VariantiRNS5_9CallErrorE+152)
  native: pc 0000000000d73958  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+328)
  native: pc 0000000000cbe3a8  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN12MessageQueue14_call_functionEP6ObjectRK10StringNamePK7Variantib+252)
  native: pc 0000000000cbe5e8  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN12MessageQueue5flushEv+180)
  native: pc 0000000000080300  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN4Main9iterationEv+808)
  native: pc 00000000000506d4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10OS_Android17main_loop_iterateEv+20)
  native: pc 000000000005e46c  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+3072)
  native: pc 00000000016b9afd  /data/app/com.algunsnerds.mathtablegame-1/oat/arm/base.odex

```

From 20 users I had one bug on the game (that above). Is solvable this kind of bug?

**Steps to reproduce:**
unknown, or maybe just open the game.

**Link to minimal example project:**
