### ISSUE TITLE
Changing the Boot Splash background color does not reflect in the web export

### ISSUE THREAD

**Issue by itsabhiaryan** [godotengine/godot#96874]
### Tested versions

Godot_v4.3-stable_win64

### System information

Windows 10 Pro - Godot_v4.3-stable_win64 - Compatibility 

### Issue description

Changing the Boot Splash background color does not reflect in the web export. I even tried to Run directly from the Editor but same result. (Run in Browser). 
or Export Web build and Check Background

### Steps to reproduce

Project Settings -> Application -> Boot Splash -> BG Color -> Set any Color 
This change project.godot -> boot_splash/bg_color=Color(1, 0, 0, 1)

Run directly from Editor but same result. 

### Minimal reproduction project (MRP)

[bootsplashbgcolor.zip](https://github.com/user-attachments/files/16969162/bootsplashbgcolor.zip)

**Comment by patwork** [comment]
At this point, the HTML template changed in 4.3 only supports boot splash image. Expansion to include more parameters from the `application/boot_splash` setting will require adding more variables passed during export.

For now, I can suggest changing the background using CSS style inside `Head Include` field, for example:

```css
<style>
#status { background-color: red; }
</style>
```

or even more fancy:

```css
<style>
#status { background: radial-gradient(circle, rgba(15,15,121,1) 0%, rgba(25,224,56,1) 100%); }
</style>
```
